services:
  inv-mgmt:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: inv-mgmt:production
    container_name: inv-mgmt-production
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - DB_HOST=${DOCKER_DB_HOST}
      - DB_USER=${DOCKER_DB_USER}
      - DB_PASSWORD=${DOCKER_DB_PASSWORD}
      - DB_NAME=${DOCKER_DB_NAME}
      - DB_PORT=${DOCKER_DB_PORT:-5432}
      - DATABASE_URL=${DOCKER_DATABASE_URL}
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:16.2
    environment:
      - POSTGRES_USER=${DOCKER_DB_USER}
      - POSTGRES_PASSWORD=${DOCKER_DB_PASSWORD}
      - POSTGRES_DB=${DOCKER_DB_NAME}
    volumes:
      - app-data:/var/lib/postgresql/data

volumes:
  app-data:
    driver: local
